// Export pages
export '/pages/main_notifications/main_notifications_widget.dart'
    show MainNotificationsWidget;
export '/pages/main_users/main_users_widget.dart' show MainUsersWidget;
export '/pages/main_recent/main_recent_widget.dart' show MainRecentWidget;
export '/pages/main_profile/main_profile_widget.dart' show MainProfileWidget;
export '/pages/main_dashboard/main_dashboard_widget.dart'
    show MainDashboardWidget;
export '/pages/transaction_history/transaction_history_widget.dart'
    show TransactionHistoryWidget;
export '/template_pages/responsive_profile/responsive_profile_widget.dart'
    show ResponsiveProfileWidget;
export '/template_pages/responsive_test/responsive_test_widget.dart'
    show ResponsiveTestWidget;
export '/pages/main_admin/main_admin_widget.dart' show MainAdminWidget;
export '/pages/create_player_page/create_player_page_widget.dart'
    show CreatePlayerPageWidget;
export '/pages/create_tournament_page/create_tournament_page_widget.dart'
    show CreateTournamentPageWidget;
export '/pages/link_players_to_tournament3rd/link_players_to_tournament3rd_widget.dart'
    show LinkPlayersToTournament3rdWidget;
export '/pages/create_club_page/create_club_page_widget.dart'
    show CreateClubPageWidget;
export '/pages/list_clubs_page/list_clubs_page_widget.dart'
    show ListClubsPageWidget;
export '/pages/list_players_page/list_players_page_widget.dart'
    show ListPlayersPageWidget;
export '/pages/edit_tournament_page/edit_tournament_page_widget.dart'
    show EditTournamentPageWidget;
export '/pages/list_tournaments_page/list_tournaments_page_widget.dart'
    show ListTournamentsPageWidget;
export '/pages/edit_club_page/edit_club_page_widget.dart'
    show EditClubPageWidget;
export '/pages/edit_player_page/edit_player_page_widget.dart'
    show EditPlayerPageWidget;
export '/pages/link_players_to_tournament1st/link_players_to_tournament1st_widget.dart'
    show LinkPlayersToTournament1stWidget;
export '/pages/link_players_to_tournament2nd/link_players_to_tournament2nd_widget.dart'
    show LinkPlayersToTournament2ndWidget;
export '/pages/link_players_to_tournament4th/link_players_to_tournament4th_widget.dart'
    show LinkPlayersToTournament4thWidget;
export '/pages/create_tournament_event1st/create_tournament_event1st_widget.dart'
    show CreateTournamentEvent1stWidget;
export '/pages/create_tournament_event2nd/create_tournament_event2nd_widget.dart'
    show CreateTournamentEvent2ndWidget;
export '/pages/create_tournament_event3rd/create_tournament_event3rd_widget.dart'
    show CreateTournamentEvent3rdWidget;
export '/pages/edit_tournament_event1st/edit_tournament_event1st_widget.dart'
    show EditTournamentEvent1stWidget;
export '/pages/edit_tournament_event2nd/edit_tournament_event2nd_widget.dart'
    show EditTournamentEvent2ndWidget;
export '/pages/edit_tournament_event3rd/edit_tournament_event3rd_widget.dart'
    show EditTournamentEvent3rdWidget;
export '/pages/edit_tournament_event4th/edit_tournament_event4th_widget.dart'
    show EditTournamentEvent4thWidget;
export '/pages/create_tournament_match1st/create_tournament_match1st_widget.dart'
    show CreateTournamentMatch1stWidget;
export '/pages/create_tournament_match2nd/create_tournament_match2nd_widget.dart'
    show CreateTournamentMatch2ndWidget;
export '/pages/create_tournament_match3rd/create_tournament_match3rd_widget.dart'
    show CreateTournamentMatch3rdWidget;
export '/pages/edit_tournament_match1st/edit_tournament_match1st_widget.dart'
    show EditTournamentMatch1stWidget;
export '/pages/edit_tournament_match2nd/edit_tournament_match2nd_widget.dart'
    show EditTournamentMatch2ndWidget;
export '/pages/edit_tournament_match3rd/edit_tournament_match3rd_widget.dart'
    show EditTournamentMatch3rdWidget;
export '/pages/edit_tournament_match4th/edit_tournament_match4th_widget.dart'
    show EditTournamentMatch4thWidget;
